#PBS -q class
#PBS -l nodes=1:m2090
#PBS -l walltime=00:01:00
#PBS -N prj-ga

# Changes to the directory we were in when we
# submit the job:

cd $PBS_O_WORKDIR

# Runs a bunch of standard command-line
# utilities, just as an example:

echo "Script began:" `date`
echo "Node:" `hostname`
echo "Current directory: ${PWD}"

echo ""
echo "=== Running TSP-CUDA ... ==="
./tsp-cuda data/problems/a280.tsp odata/solutions/a280.opt.tour p1024 g1024

echo ""
echo "=== Done! ==="

# eof
